[config]
version_check = false

[templates.quickshell]
input_path = "templates/quickshell-colors.json"
output_path = "./generated/clavis/colors.json"

[templates.btop]
input_path = "templates/btop.theme"
output_path = "./generated/btop/themes/clavis.theme"

[templates.cava]
input_path = "templates/cava-colors.ini"
output_path = "./generated/cava/colors.ini"

[templates.kitty]
input_path = "templates/kitty-colors.conf"
output_path = "./generated/kitty/colors.conf"

[templates.fcitx5]
input_path = "templates/fcitx5-theme.conf"
output_path = "./generated/fcitx5/Matugen/theme.conf"

[templates.niri]
input_path = "templates/niri-colors.kdl"
output_path = "./generated/niri/colors.kdl"

[templates.yazi]
input_path = "templates/yazi-theme.toml"
output_path = "./generated/yazi/theme.toml"

[templates.zsh_prompt]
input_path = "templates/zsh-prompt-colors.zsh"
output_path = "./generated/zsh/prompt-colors.zsh"

[templates.fcitx5_panel_svg]
input_path = "templates/fcitx5-panel.svg"
output_path = "./generated/fcitx5/Matugen/panel.svg"

[templates.fcitx5_highlight_svg]
input_path = "templates/fcitx5-highlight.svg"
output_path = "./generated/fcitx5/Matugen/highlight.svg"
