shell /usr/bin/zsh


font_size 15


# window
hide_window_decorations         yes
#window_padding_width            15
background_opacity              0.8
background_blur                 30

# 字体设置
font_family	JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15

# 设置备用字体
symbol_map U+4E00-U+9FFF LXGW WenKai GB Screen
symbol_map U+3400-U+4DBF LXGW WenKai GB Screen
symbol_map U+20000-U+2A6DF LXGW WenKai GB Screen
symbol_map U+2A700-U+2B73F LXGW WenKai GB Screen
symbol_map U+2B740-U+2B81F LXGW WenKai GB Screen
symbol_map U+2B820-U+2CEAF LXGW WenKai GB Screen

# 开启光标拖尾功能（数字代表拖尾的插值系数/长度，推荐设为 1 或 3）
cursor_trail 3

# （可选）控制拖尾消散的速度。
# 接受两个小数，分别代表最快和最慢的消散时间（单位：秒）
cursor_trail_decay 0.1 0.4

# （可选）触发拖尾的移动阈值。
# 设置为 2 表示光标一次性移动超过 2 个字符距离时才显示拖尾
cursor_trail_start_threshold 2
